### ISSUE TITLE
LAMMPS / MatGL / CUDA - Python cannot find NumPy when called by LAMMPS

### ISSUE THREAD

**Issue by justin-gedge** [advancesoftcorp/lammps#13]
Using current release of LAMMPS [based-on-lammps_2Aug2023] to leverage MatGL/CUDA.  I have my own custom Python3 installation with MatGL and it's dependencies installed.  When I build LAMMPS and have it call Python, there are issues with NumPy.

```
ERROR: Cannot initialize python for pair_coeff of M3GNet. (src/ML-M3GNET/pair_m3gnet.cpp:490)
Last command: pair_coeff * * M3Gnet-MP-2021.2.8-PES Au    # specify GNN parameter checkpoint file
```

The corresponding Python dump follows:

```
Traceback (most recent call last):
  File "/data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyObject_SelfIter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/bin/python3"
  * The NumPy version is: "1.26.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyObject_SelfIter


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/tools/build/ubuntu_22.04/lammps/asc_2Aug2023_matgl0.9.1_cuda118/01_test_lammps/./matgl_driver.py", line 33, in <module>
    from ase import Atoms
  File "/data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/ase/__init__.py", line 17, in <module>
    from ase.atom import Atom
  File "/data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/ase/atom.py", line 3, in <module>
    import numpy as np
  File "/data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

I added following code to the matgl_driver.py to show envvars:

```
import os
import sys

#print( "PYTHONPATH: %s" % ( os.environ.get( 'PYTHONPATH' ) ) )
#print( "PATH:       %s" % ( os.environ.get( 'PATH'       ) ) )
#print( "sys.path:   %s" % ( sys.path                   ) )

print( "PYTHONHOME:" )
print( "    %s" % ( os.environ.get( 'PYTHONHOME' ) ) )

print( "PYTHONPATH:" )
if os.environ.get( 'PYTHONPATH' ):
    for item in os.environ.get( 'PYTHONPATH' ).split( ':'):
        print( "    %s" % ( item ) )
else:
    print( "    %s" % ( os.environ.get( 'PYTHONPATH' ) ) )

print( "PATH:" )
for item in os.environ.get( 'PATH' ).split( ':' ):
    print( "    %s" % ( item ) )
print( "sys.path:")
for item in sys.path:
    print( "    %s" % ( item ) )

```

The value of envvars from Python when called by LAMMPS follows:

```
PYTHONHOME:
    None
PYTHONPATH:
    None
PATH:
    /data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/bin
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    /usr/games
    /usr/local/games
    /snap/bin
sys.path:
    /data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python310.zip
    /data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10
    /data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/lib-dynload
    /data/tools/target/ubuntu_22.04/python/3.10.13_matgl_0.9.1_cuda_11.8/lib/python3.10/site-packages
    .
    ./matgl_driver.py
```

I believe this may be solved by setting PYTHONHOME and/or PYTHONPATH, but have not been able to resolve this with my attempts.  Guidance on why Python interpreter cannot find it's `numpy` package is appreciated.

**Comment by naveenmohandas** [comment]
Hi,
 I have also been facing this issue, not sure if you managed to fix this. For me, the issue was when installing it in a cluster with a conda environment. 

What worked for me was to build the packages using an interactive job (i.e to run on the main nodes instead of login nodes) to build the packages. 

I do not use make-install, but directly call the lmp binary in the build directory after activating the conda environment to run lammps. 

Hope it helps.

**Comment by advancesoftcorp** [comment]
Please check the versions of numpy, ase and the other python modules.
