### ISSUE TITLE
Troubles when making ML-M3GNET package

### ISSUE THREAD

**Issue by ZLI-afk** [advancesoftcorp/lammps#17]
I try to compile LAMMPS with `ML-M3GNET` package included on my Ubuntu with `cmake`:
```shell
cd lammps
mkdir build
cd build
cmake ../cmake -D PKG_ML-M3GNET=ON
cmake --build .
```
but got following **error** when building:
```
[ 54%] Building CXX object CMakeFiles/lammps.dir/lammps/src/force.cpp.o
In file included from /lammps/build/styles/style_pair.h:15,
                 from /lammps/src/force.cpp:21:
/lammps/src/ML-M3GNET/pair_m3gnet.h:17:10: fatal error: Python.h: No such file or directory
   17 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
```
Could you please help to check whether there is anything I missed?

Many thanks.

**Comment by naveenmohandas** [comment]
you also need to compile with PKG_PYTHON to use M3GNET. Use 'cmake ../cmake -D PKG_ML-M3GNET=ON PKG_PYTHON=ON' and it should work.

**Comment by ZLI-afk** [comment]
> you also need to compile with PKG_PYTHON to use M3GNET. Use 'cmake ../cmake -D PKG_ML-M3GNET=ON PKG_PYTHON=ON' and it should work.

Thanks for your reply.

I have solved the compiling issue according to your advice. But when I tried to run the `M3GNET` case located at `lammps/examples`, following Error appears. Do you have any idea on how to fix this? Thanks!

```
lmp < inp.lammps 
LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
/opt/mamba/bin/python3
Reading data file ...
  orthogonal box = (0 0 0) to (5.1499664 5.1499664 5.1499664)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  12 atoms
  read_data CPU = 0.001 seconds
Traceback (most recent call last):
  File "/opt/mamba/lib/python3.10/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/opt/mamba/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/opt/mamba/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mamba/lib/python3.10/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/opt/mamba/lib/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/opt/mamba/lib/python3.10/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/opt/mamba/bin/python3"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lammps/examples/M3GNET/../../potentials/M3GNET/m3gnet_driver.py", line 8, in <module>
    from ase import Atoms
  File "/opt/mamba/lib/python3.10/site-packages/ase/__init__.py", line 17, in <module>
    from ase.atom import Atom
  File "/opt/mamba/lib/python3.10/site-packages/ase/atom.py", line 3, in <module>
    import numpy as np
  File "/opt/mamba/lib/python3.10/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
ERROR: Cannot initialize python for pair_coeff of M3GNet. (src/ML-M3GNET/pair_m3gnet.cpp:524)
Last command: pair_coeff    * *  MP-2021.2.8-EFS  Zr O  # M3GNet <https://github.com/materialsvirtuallab/m3gnet> will be called
```

**Comment by naveenmohandas** [comment]
From what I see it is most likely a conflict of environments. Have you installed m3gnet python packages system wide or in a specific environment?

If you have installed it in a specific environment you have to make sure it is active and Lammps during compiling selects it as the python environment. It is a bit tricky with python environments and Lammps.

**Comment by ZLI-afk** [comment]
> From what I see it is most likely a conflict of environments. Have you installed m3gnet python packages system wide or in a specific environment?
> 
> If you have installed it in a specific environment you have to make sure it is active and Lammps during compiling selects it as the python environment. It is a bit tricky with python environments and Lammps.

I haven't installed `m3gnet` package in advance. I just tried compile from scratch under a system wide python environment. However, after I installed the `m3gnet` via `pip` and re-compiled the lammps, the same error appears again .

If it is not too much trouble, could you please provide an installation instruction step by step on an Ubuntu sys with basic Python environment from scratch? That will be helpful. Thanks!

**Comment by bawanglong-2** [comment]
I want to know how to deal it?

![Image](https://github.com/user-attachments/assets/def7bda4-31b6-444f-afba-93b8145ee17f)
